/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNamespaceDialog: typeof import('./components/addNamespaceDialog.vue')['default']
    AddOrEditProjectNameDialog: typeof import('./components/AddOrEditProjectNameDialog.vue')['default']
    AddWarehouseDialog: typeof import('./components/addWarehouseDialog.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AssignToRoleDialogSingle: typeof import('./components/assignToRoleDialogSingle.vue')['default']
    AuthenticationDisabledWarningBanner: typeof import('./components/AuthenticationDisabledWarningBanner.vue')['default']
    BranchVisualization: typeof import('./components/BranchVisualization.vue')['default']
    BreadcrumbsFromUrl: typeof import('./components/BreadcrumbsFromUrl.vue')['default']
    ComputeConnectDialog: typeof import('./components/ComputeConnectDialog.vue')['default']
    DeletingDialog: typeof import('./components/deletingDialog.vue')['default']
    DialogDelete: typeof import('./components/DialogDelete.vue')['default']
    DialogDeleteConfirm: typeof import('./components/dialogDeleteConfirm.vue')['default']
    EULA: typeof import('./components/EULA.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    PermissionManager: typeof import('./components/PermissionManager.vue')['default']
    ProjectManager: typeof import('./components/ProjectManager.vue')['default']
    ProjectStatistics: typeof import('./components/ProjectStatistics.vue')['default']
    RenameWarehouseDialog: typeof import('./components/RenameWarehouseDialog.vue')['default']
    RoleDialog: typeof import('./components/roleDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackbarMessage: typeof import('./components/SnackbarMessage.vue')['default']
    StatisticsDialog: typeof import('./components/StatisticsDialog.vue')['default']
    TaskConfigDialog: typeof import('./components/TaskConfigDialog.vue')['default']
    TaskDetails: typeof import('./components/TaskDetails.vue')['default']
    TaskManager: typeof import('./components/TaskManager.vue')['default']
    UserManager: typeof import('./components/UserManager.vue')['default']
    UserRenameDialog: typeof import('./components/UserRenameDialog.vue')['default']
    WarehouseActionsMenu: typeof import('./components/WarehouseActionsMenu.vue')['default']
    WarehouseAzure: typeof import('./components/WarehouseAzure.vue')['default']
    WarehouseGCS: typeof import('./components/WarehouseGCS.vue')['default']
    WarehouseJSON: typeof import('./components/WarehouseJSON.vue')['default']
    WarehouseS3: typeof import('./components/WarehouseS3.vue')['default']
  }
}
