/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddOrEditProjectDialog: typeof import('@lakekeeper/console-components/AddOrEditProjectDialog.vue')['default']
    AddOrEditProjectNameDialog: typeof import('./components/AddOrEditProjectNameDialog.vue')['default']
    AddWarehouseDialog: typeof import('./components/addWarehouseDialog.vue')['default']
    AuthenticationDisabledWarningBanner: typeof import('./components/AuthenticationDisabledWarningBanner.vue')['default']
    BreadcrumbsFromUrl: typeof import('./components/BreadcrumbsFromUrl.vue')['default']
    ComputeConnectDialog: typeof import('./components/ComputeConnectDialog.vue')['default']
    DeletingDialog: typeof import('./components/deletingDialog.vue')['default']
    DialogDelete: typeof import('./components/DialogDelete.vue')['default']
    DialogDeleteConfirm: typeof import('./components/dialogDeleteConfirm.vue')['default']
    EULA: typeof import('./components/EULA.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    ProjectManager: typeof import('./components/ProjectManager.vue')['default']
    ProjectStatistics: typeof import('./components/ProjectStatistics.vue')['default']
    RenameWarehouseDialog: typeof import('./components/RenameWarehouseDialog.vue')['default']
    RoleDialog: typeof import('./components/roleDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticsDialog: typeof import('./components/StatisticsDialog.vue')['default']
    WarehouseActionsMenu: typeof import('./components/WarehouseActionsMenu.vue')['default']
    WarehouseAzure: typeof import('./components/WarehouseAzure.vue')['default']
    WarehouseGCS: typeof import('./components/WarehouseGCS.vue')['default']
    WarehouseJSON: typeof import('./components/WarehouseJSON.vue')['default']
    WarehouseS3: typeof import('./components/WarehouseS3.vue')['default']
  }
}
