/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bootstrap': RouteRecordInfo<
      '/bootstrap',
      '/bootstrap',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/callback': RouteRecordInfo<
      '/callback',
      '/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/license': RouteRecordInfo<
      '/license',
      '/license',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/logout': RouteRecordInfo<
      '/logout',
      '/logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notfound': RouteRecordInfo<
      '/notfound',
      '/notfound',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/roles/': RouteRecordInfo<
      '/roles/',
      '/roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/roles/[id]': RouteRecordInfo<
      '/roles/[id]',
      '/roles/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/server-offline': RouteRecordInfo<
      '/server-offline',
      '/server-offline',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server-settings': RouteRecordInfo<
      '/server-settings',
      '/server-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user-profile': RouteRecordInfo<
      '/user-profile',
      '/user-profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/warehouse/': RouteRecordInfo<
      '/warehouse/',
      '/warehouse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/warehouse/[id]': RouteRecordInfo<
      '/warehouse/[id]',
      '/warehouse/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/warehouse/[id].namespace.[nsid]': RouteRecordInfo<
      '/warehouse/[id].namespace.[nsid]',
      '/warehouse/:id/namespace/:nsid',
      { id: ParamValue<true>, nsid: ParamValue<true> },
      { id: ParamValue<false>, nsid: ParamValue<false> },
      | never
    >,
    '/warehouse/[id].namespace.[nsid].table.[tid]': RouteRecordInfo<
      '/warehouse/[id].namespace.[nsid].table.[tid]',
      '/warehouse/:id/namespace/:nsid/table/:tid',
      { id: ParamValue<true>, nsid: ParamValue<true>, tid: ParamValue<true> },
      { id: ParamValue<false>, nsid: ParamValue<false>, tid: ParamValue<false> },
      | never
    >,
    '/warehouse/[id].namespace.[nsid].view.[vid]': RouteRecordInfo<
      '/warehouse/[id].namespace.[nsid].view.[vid]',
      '/warehouse/:id/namespace/:nsid/view/:vid',
      { id: ParamValue<true>, nsid: ParamValue<true>, vid: ParamValue<true> },
      { id: ParamValue<false>, nsid: ParamValue<false>, vid: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/bootstrap.vue': {
      routes:
        | '/bootstrap'
      views:
        | never
    }
    'src/pages/callback.vue': {
      routes:
        | '/callback'
      views:
        | never
    }
    'src/pages/license.vue': {
      routes:
        | '/license'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/logout.vue': {
      routes:
        | '/logout'
      views:
        | never
    }
    'src/pages/notfound.vue': {
      routes:
        | '/notfound'
      views:
        | never
    }
    'src/pages/roles/index.vue': {
      routes:
        | '/roles/'
      views:
        | never
    }
    'src/pages/roles/[id].vue': {
      routes:
        | '/roles/[id]'
      views:
        | never
    }
    'src/pages/server-offline.vue': {
      routes:
        | '/server-offline'
      views:
        | never
    }
    'src/pages/server-settings.vue': {
      routes:
        | '/server-settings'
      views:
        | never
    }
    'src/pages/user-profile.vue': {
      routes:
        | '/user-profile'
      views:
        | never
    }
    'src/pages/warehouse/index.vue': {
      routes:
        | '/warehouse/'
      views:
        | never
    }
    'src/pages/warehouse/[id].vue': {
      routes:
        | '/warehouse/[id]'
      views:
        | never
    }
    'src/pages/warehouse/[id].namespace.[nsid].vue': {
      routes:
        | '/warehouse/[id].namespace.[nsid]'
      views:
        | never
    }
    'src/pages/warehouse/[id].namespace.[nsid].table.[tid].vue': {
      routes:
        | '/warehouse/[id].namespace.[nsid].table.[tid]'
      views:
        | never
    }
    'src/pages/warehouse/[id].namespace.[nsid].view.[vid].vue': {
      routes:
        | '/warehouse/[id].namespace.[nsid].view.[vid]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
