name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install Packages and Build Application
        run: |
          npm ci
          npm run build

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          path: dist
          if-no-files-found: error
